class AddEvenMoreIndexes < ActiveRecord::Migration
  def self.up
    add_index :alumni, :organisation_id
    add_index :alumni, :person_id
    add_index :archive_parts, :donation_id
    add_index :article_languages, :article_id
    add_index :articles, :periodical_id 
    add_index :articles, :periodical_copy_id
    add_index :audio_video_languages, :audio_video_title_id
    add_index :audio_video_media, :copy_of_id
    add_index :audio_video_media, :donation_id
    add_index :audio_video_title_on_media, :audio_video_title_id
    add_index :audio_video_title_on_media, :audio_video_medium_id
    add_index :audio_video_title_on_media, :source_id
    add_index :book_copies, :book_title_id
    add_index :book_copies, :donation_id
    add_index :book_title_impressums, :book_title_id
    add_index :book_title_impressums, :impressum_id
    add_index :book_title_languages, :book_title_id
    add_index :book_titles, :part_of_book_title_id
    add_index :donations, :organisation_id
    add_index :donations, :donor_person_id
    add_index :donations, :donor_organisation_id
    add_index :ephemera, :source_id
    add_index :ephemera, :donation_id
    add_index :ephemerum_languages, :ephemerum_id
    add_index :festivals, :organisation_id
    add_index :grants, :production_id
    add_index :ico_titles, :part_of_ico_title_id
    add_index :ico_titles, :donation_id
    add_index :ico_titles, :archive_part_id
    add_index :impressums, :organisation_id
    add_index :orders, :organisation_id
    add_index :organisation_relations, :from_id
    add_index :organisation_relations, :to_id
    add_index :periodical_copies, :periodical_id
    add_index :periodical_copies, :donation_id
    add_index :periodical_copies, :part_of_copy_id
    add_index :periodical_impressums, :periodical_id
    add_index :person_isaars, :person_id
    add_index :person_isaars, :alias_of_id
    add_index :production_languages, :production_id
    add_index :productions, :revival_of_id
    add_index :shows, :production_id
    add_index :shows, :room_id
    add_index :shows, :organisation_id  
  end

  def self.down
    remove_index :shows, :organisation_id
    remove_index :shows, :room_id
    remove_index :shows, :production_id
    remove_index :productions, :revival_of_id
    remove_index :production_languages, :production_id
    remove_index :person_isaars, :alias_of_id
    remove_index :person_isaars, :person_id
    remove_index :periodical_impressums, :periodical_id
    remove_index :periodical_copies, :part_of_copy_id
    remove_index :periodical_copies, :donation_id
    remove_index :periodical_copies, :periodical_id
    remove_index :organisation_relations, :to_id
    remove_index :organisation_relations, :from_id
    remove_index :orders, :organisation_id
    remove_index :impressums, :organisation_id
    remove_index :ico_titles, :archive_part_id
    remove_index :ico_titles, :donation_id
    remove_index :ico_titles, :part_of_ico_title_id
    remove_index :grants, :production_id
    remove_index :festivals, :organisation_id
    remove_index :ephemerum_languages, :ephemerum_id
    remove_index :ephemera, :donation_id
    remove_index :ephemera, :source_id
    remove_index :donations, :donor_organisation_id
    remove_index :donations, :donor_person_id
    remove_index :donations, :organisation_id
    remove_index :book_titles, :part_of_book_title_id
    remove_index :book_title_languages, :book_title_id
    remove_index :book_title_impressums, :impressum_id
    remove_index :book_title_impressums, :book_title_id
    remove_index :book_copies, :donation_id
    remove_index :book_copies, :book_title_id
    remove_index :audio_video_title_on_media, :source_id
    remove_index :audio_video_title_on_media, :audio_video_medium_id
    remove_index :audio_video_title_on_media, :audio_video_title_id
    remove_index :audio_video_media, :donation_id
    remove_index :audio_video_media, :copy_of_id
    remove_index :audio_video_languages, :audio_video_title_id
    remove_index :articles, :periodical_copy_id
    remove_index :articles, :periodical_id
    remove_index :article_languages, :article_id
    remove_index :archive_parts, :donation_id
    remove_index :alumni, :person_id
    remove_index :alumni, :organisation_id
  end
end
